#!/bin/bash
#####################################
APP_NAME=jmess
######################################
## Created by Juan-Pablo Caceres

#Cleanup
#rm $APP_NAME.pro
#rm Makefile
#echo "cleanup done"

#Create project (.pro) file
qmake -project -o $APP_NAME.pro

echo "qmake-qt4 .pro built."

#Create Makefile
qmake -makefile -o Makefile \
"QT+=xml" \
"QMAKE_CLEAN+=$APP_NAME" \
"LIBS+=-ljack -framework CoreAudio" \
"TARGET=$APP_NAME" \
$APP_NAME.pro

echo "done"
