#!/bin/bash
#####################################
APP_NAME=jmess
APP_NAME_QUOTES=\\\"$APP_NAME\\\"
######################################

rm Makefile
echo "Makefile deleted"

qmake-qt4 -project -o $APP_NAME.pro
echo "qmake-qt4 .pro built."

qmake-qt4 -makefile -unix -o Makefile \
"QMAKE_CXXFLAGS+=-Wno-deprecated -pg -g" \
"OBJECTS_DIR=obj" "MOC_DIR=moc" \
"unix:LIBS+=-Xlinker -ljack -lpthread -lrt" \
"QT+=xml" \
$APP_NAME.pro

echo "done"
